<a href="https://colab.research.google.com/github/Audraggc/DSSC2.2/blob/main/ActInt_Pruebate_M2_T2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Actividad de Integración Pruebate Módulo 2 Tema 2

In [ ]:
import numpy as np

1.	Crea un arreglo de numpy llamado listaDatos de numpy con los siguientes valores [45, 67, 23, 51, 89, 100, 23, 46, 57, 12, 1, 87, 23, 69, 33, 18, 87, 45, 73, 28]

In [ ]:
listaDatos = np.array([45, 67, 23, 51, 89, 100, 23, 46, 57, 12, 1, 87, 23, 69, 33, 18, 87, 45, 73, 28])
print('listaDatos: \n', listaDatos)

listaDatos: 
 [ 45  67  23  51  89 100  23  46  57  12   1  87  23  69  33  18  87  45
  73  28]


2.	Crea una matriz de numpy de 5x4 llamado matrizA con los siguientes valores [[34, 61, 0, 12], [98, 53, 76, 2], [19, 56, 87, 32], [100, 62, 91, 21], [84, 50, 41, 3]]


In [ ]:
 matrizA = np.array([[34, 61, 0, 12], [98, 53, 76, 2], [19, 56, 87, 32], [100, 62, 91, 21], [84, 50, 41, 3]])
 print('matrizA :\n',matrizA)

matrizA :
 [[ 34  61   0  12]
 [ 98  53  76   2]
 [ 19  56  87  32]
 [100  62  91  21]
 [ 84  50  41   3]]


3.	Convierte el arreglo listaDatos a una matriz de 5x4 llamada MatB

In [ ]:
matrizB = listaDatos.reshape((5,4))
print('matrizB :\n', matrizB)

matrizB :
 [[ 45  67  23  51]
 [ 89 100  23  46]
 [ 57  12   1  87]
 [ 23  69  33  18]
 [ 87  45  73  28]]


4.	Determinar el valor mínimo y máximo de la primera matriz

In [ ]:
print('Valor mínimo de matrizA: ', matrizA.min())
print('Valor máximo de matrizA: ', matrizA.max())

Valor mínimo de matrizA:  0
Valor máximo de matrizA:  100


5.	Calcular el promedio de todas las columnas de la primera matriz

In [ ]:
print('Promedio de cada una de las columnas de matrizA: ', matrizA.mean(axis=0))

Promedio de todas las columnas de matrizA:  [67.  56.4 59.  14. ]


6.	Calcular la suma de todos los elementos de la segunda y tercera fila de la primera matriz

In [ ]:
print('Suma de todos los elementos de la segunda y tercera fila de la matrizA: ', matrizA[1:3:1, :].sum())

Suma de todos los elementos de la segunda y tercera fila de la matrizA:  423


7.	Sumar las dos matrices

In [ ]:
print('Resultado de la suma de matrices: \n', matrizA + matrizB)


Resultado de la suma de matrices: 
 [[ 79 128  23  63]
 [187 153  99  48]
 [ 76  68  88 119]
 [123 131 124  39]
 [171  95 114  31]]


8.	Obtener la multiplicación de ambas matrices

In [ ]:
matrizB = matrizB.reshape((4, 5))
print('Resultado de la multiplicación de matrices: \n', matrizA @ matrizB)

Resultado de la multiplicación de matrices: 
 [[ 7846  4725  4128  6087  4094]
 [ 9822 14571  6530 13409 11922]
 [ 7118 12914  6454 12500  6130]
 [11169 17870  8190 16446 13235]
 [ 8875 10606  5310 10182  9513]]


9.	Obtener la transpuesta de la matrizB



In [ ]:
print('Transpuesta de la matrizB: \n', matrizB.transpose())

Transpuesta de la matrizB: 
 [[ 45 100   1  18]
 [ 67  23  87  87]
 [ 23  46  23  45]
 [ 51  57  69  73]
 [ 89  12  33  28]]
